SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;