# SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
# FROM ITEM_INFO I
# WHERE I.ITEM_ID NOT IN (
#     SELECT PARENT_ITEM_ID
#     FROM ITEM_TREE
#     WHERE PARENT_ITEM_ID IS NOT NULL  -- 이 줄이 없으면 아무것도 출력안됨
# )
# ORDER BY I.ITEM_ID DESC;


SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
LEFT JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.ITEM_ID IS NULL  -- T.ITEM_ID로 1,3만 남고 나머지는 삭제됨
ORDER BY I.ITEM_ID DESC;