-- 1. 서브쿼리
# SELECT ID, 
#     (
#         SELECT COUNT(*)
#         FROM ECOLI_DATA D
#         WHERE E.ID = D.PARENT_ID
#     ) AS CHILD_COUNT
# FROM ECOLI_DATA E
# ORDER BY ID;



-- 2. LEFT JOIN
SELECT E.ID, COUNT(D.ID) AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN ECOLI_DATA D ON E.ID = D.PARENT_ID
GROUP BY E.ID
ORDER BY E.ID;