SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    SELECT O.SALES_DATE, O.PRODUCT_ID, O.USER_ID, O.SALES_AMOUNT
    FROM ONLINE_SALE O
    WHERE O.SALES_DATE >= '2022-03-01' AND O.SALES_DATE < '2022-04-01'
    
    UNION ALL
    
    SELECT F.SALES_DATE, F.PRODUCT_ID, NULL AS USER_ID, F.SALES_AMOUNT
    FROM OFFLINE_SALE F
    WHERE F.SALES_DATE >= '2022-03-01' AND F.SALES_DATE < '2022-04-01'
) AS S
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;