SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE ('Intact%')
    AND (O.SEX_UPON_OUTCOME LIKE ('Spayed%') OR O.SEX_UPON_OUTCOME LIKE ('Neutered%'))
    -- AND()로 묶어주지 않으면 AND를 먼저 계산하고, 그 뒤에 OR을 계산하게 됨
ORDER BY I.ANIMAL_ID;