SELECT H.HISTORY_ID, 
    FLOOR(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (1- IFNULL(P.DISCOUNT_RATE,0)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE -- C+H에 LEFT JOIN
 AND ( CASE
          WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 90 THEN '90일 이상'
          WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 30 THEN '30일 이상'
          WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 7 THEN '7일 이상'
          ELSE NULL
      END
 ) = P.DURATION_TYPE  -- DURATION_TYPE이 연결 -> RATE 자동 연결
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;