SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
WHERE M.MEMBER_ID IN ( -- = 대신 IN 해야 동률 출력 가능
    SELECT RR.MEMBER_ID
    FROM REST_REVIEW RR
    GROUP BY RR.MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(c) -- MAX를 바로 쓸 수 없음
        FROM (
            SELECT COUNT(*) AS c
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) t
    )
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;