# SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE (SKILL_CODE & 256 > 0) OR (SKILL_CODE & 1024 > 0)
# ORDER BY ID;

# -- 코드를 작성해주세요
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, SKILLCODES S
WHERE S.NAME IN ('C#', 'Python') AND (D.SKILL_CODE & S.CODE > 0)
ORDER BY D.ID;