SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F
WHERE F.BOARD_ID = (
    SELECT B.BOARD_ID
    FROM USED_GOODS_BOARD B
    WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
    -- B.VIEWS = MAX(B.VIEWS) 안됨
    -- 서브쿼리 + 서브쿼리가 쓰기 싫다면 -> 여기서 WHERE 쓰지 말고 ORDER BY VIEWS + LIMIT 1 걸어주기
)
ORDER BY F.FILE_ID DESC;