SELECT P.CATEGORY, P.PRICE AS MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P
WHERE P.CATEGORY IN ('과자', '국', '김치', '식용유')
AND P.PRICE = (
    SELECT MAX(F.PRICE)
    FROM FOOD_PRODUCT F
    WHERE P.CATEGORY = F.CATEGORY
)
ORDER BY MAX_PRICE DESC;